apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: argocd         # Added namespace
spec:
  type: LoadBalancer
  selector:
    app: fastapi         # Send traffic to Pods with this label
  ports:
  - port: 80            # The port the service exposes internally
    targetPort: 80      # Must match the Deployment's containerPort
  #  nodePort: 30007     # Accessible via <NodeIP>:30007
