apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  # Use the Service names from your other files
  POSTGRES_HOST: "postgres-svc" 
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "write_around_db"

  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

