apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: argocd
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"

  # Format: postgresql://user:password@host:port/dbname
  DATABASE_URL: "postgresql+asyncpg://postgres:password@postgres-svc:5432/write_around_db"

  # Format: redis://host:port/db_number
  REDIS_URL: "redis://redis-svc:6379/0"
